### ISSUE TITLE
大佬 980这个 ssd需要折腾吗 

### ISSUE THREAD

**Issue by androidfans** [zxyboy/i9-10850K-Z490-AORUS-PRO-AX#1]
我在网上搜的, 970需要升级固件才能装, 不知道980什么情况

你这台黑果长时间不关机有问题吗 
对4k的支持完美吗

**Comment by zxyboy** [comment]
不关机可以自动休眠， 但是没有白苹果那么顺畅。

**Comment by zxyboy** [comment]
4k可以使用，三星980可以完美使用，但是好像10代的cpu不支持pcie4。

**Comment by androidfans** [comment]
我查了这个主板是支持pcie4的. 等11代的U出来了直接换掉应该就行

**Comment by androidfans** [comment]
主板应该不用再换了

**Comment by zxyboy** [comment]
是的

**Comment by zxyboy** [comment]
你黑苹果装成功了没 ？

**Comment by androidfans** [comment]
没呢. 还在选硬件.  现在显卡太难买了.  打算暂时整个rx560 等降价 不知道你这个efi能直接用吗.  我其他的硬件应该都和你一样

**Comment by lz-lee** [comment]
AirDrop 能用吗

**Comment by androidfans** [comment]
做完了.  没出现任何问题
